# nixpacks.toml

[env]
NPM_CONFIG_PRODUCTION = "false"

providers = ["node"]

[phases.setup]
# Keep default packages ("...") plus install nodejs (which includes npm)
nixPkgs = ["...", "nodejs"]

[phases.build]
cmds = [
  "npm install --include=dev",  # force install of devDependencies like Vite
  "npx vite build",             # build frontend first
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"  # then build backend
]
cacheDirectories = ["node_modules"]

[start]
cmd = "node dist/index.js"